import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DATA } from "@/data/resume";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Space_Grotesk as FontSans, Patrick_Hand, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import { Pointer } from "@/components/magicui/pointer";
import { StarField } from "@/components/star-field";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700"],
});

const fontPatrick = Patrick_Hand({
  subsets: ["latin"],
  variable: "--font-patrick",
  weight: "400",
});

const fontShareTechMono = Share_Tech_Mono({
  subsets: ["latin"],
  variable: "--font-share-tech-mono",
  weight: "400",
});

export const metadata: Metadata = {
  metadataBase: new URL(DATA.url),
  title: {
    default: `${DATA.name} — ${DATA.tagline}`,
    template: `%s | ${DATA.name}`,
  },
  description: DATA.description,
  // Use existing assets to avoid 404s
  icons: {
    icon: "/favicon.ico",
  },
  alternates: {
    canonical: "/",
  },
  keywords: [
    "Yueqiao Wang",
    "Portfolio",
    "Computer Engineering",
    "RISC-V",
    "Embedded",
    "Robotics",
    "Web Development",
    "Rose-Hulman Institute of Technology",
    "Computer Science",
    "Computer Architecture",
    "Operating System",

  ],
  authors: [{ name: DATA.name, url: DATA.url }],
  creator: DATA.name,
  publisher: DATA.name,
  // manifest: "/manifest.webmanifest",
  openGraph: {
    title: `${DATA.name} — ${DATA.tagline}`,
    description: DATA.description,
    url: DATA.url,
    siteName: `${DATA.name}`,
    locale: "en_US",
    type: "website",
    images: [
      {
        // Static file generated by scripts/generate-og.mjs — a dynamic /og route
        // is excluded from the static export and 404s in production.
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: `${DATA.name}`,
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: `${DATA.name} — ${DATA.tagline}`,
    card: "summary_large_image",
    images: ["/og.png"],
  },
  verification: {
    google: "",
    yandex: "",
  },
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased mx-auto py-12 sm:py-24 px-4 sm:px-6 lg:px-8 max-w-5xl",
          fontSans.variable,
          fontPatrick.variable,
          fontShareTechMono.variable
        )}
      >
        <ThemeProvider>
          {/* ── Background ambient layer (theme-aware) ── */}
          <div
            aria-hidden="true"
            className="pointer-events-none fixed inset-0 overflow-hidden"
            style={{ zIndex: 0 }}
          >
            {/* Light mode only: aurora animated gradients */}
            <div
              className="absolute -inset-[20%] animate-aurora-drift opacity-25 dark:opacity-0 will-change-transform"
              style={{
                backgroundImage: [
                  "radial-gradient(ellipse 80% 50% at 5%  10%, #6366f1, transparent)",
                  "radial-gradient(ellipse 60% 45% at 90% 15%, #93c5fd, transparent)",
                  "radial-gradient(ellipse 50% 60% at 50%  0%, #8b5cf6, transparent)",
                  "radial-gradient(ellipse 65% 35% at 20% 30%, #2dd4bf, transparent)",
                  "radial-gradient(ellipse 55% 50% at 80% 40%, #a5b4fc, transparent)",
                ].join(", "),
                filter: "blur(72px)",
              }}
            />
            <div
              className="absolute -inset-[20%] animate-aurora-drift-2 opacity-[0.15] dark:opacity-0 will-change-transform"
              style={{
                backgroundImage: [
                  "radial-gradient(ellipse 50% 45% at 75% 75%, #6366f1, transparent)",
                  "radial-gradient(ellipse 45% 55% at 15% 65%, #8b5cf6, transparent)",
                  "radial-gradient(ellipse 55% 40% at 85% 45%, #2dd4bf, transparent)",
                ].join(", "),
                filter: "blur(60px)",
              }}
            />
            {/* Dark mode only: deep-space nebula tints */}
            <div
              className="absolute -inset-[30%] animate-nebula-drift opacity-0 dark:opacity-100 will-change-transform"
              style={{
                backgroundImage: [
                  "radial-gradient(ellipse 75% 55% at 8%  8%,  rgba(99,102,241,0.18), transparent)",
                  "radial-gradient(ellipse 55% 50% at 92% 5%,  rgba(6,182,212,0.10),  transparent)",
                  "radial-gradient(ellipse 60% 45% at 48% 92%, rgba(139,92,246,0.14),  transparent)",
                  "radial-gradient(ellipse 40% 45% at 82% 55%, rgba(20,184,166,0.08),  transparent)",
                  "radial-gradient(ellipse 35% 40% at 25% 70%, rgba(244,114,182,0.07), transparent)",
                ].join(", "),
                filter: "blur(90px)",
              }}
            />
          </div>
          {/* ── Star canvas (dark mode only, client component) ── */}
          <StarField />
          {/* ── Content sits above (z-10) ── */}
          <div className="relative" style={{ zIndex: 10 }}>
            <TooltipProvider delayDuration={0}>
              {children}
              <Navbar />
            </TooltipProvider>
          </div>
        </ThemeProvider>
        <Pointer>
          <div className="text-2xl max-sm:hidden">👆</div>
        </Pointer>
      </body>
    </html>
  );
}
